version: "3.9"

services:

  app:
    build:
      context: ./project
      dockerfile: ./Dockerfile
    command: ["/project/app.sh"]
    volumes:
      - static_volume:/home/project/app/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod

  db:
    image: postgres:14.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/project/app/static
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  db_data:
  static_volume: